### ISSUE TITLE
How is this different from the original MaterializeCSS?

### ISSUE THREAD

**Issue by dandv** [justan0therdave/materialize#1]
Hi Dave,

I'm an [Atmosphere mod](https://atmospherejs.com/dandv) and I found [justan0therdave:materialize](https://atmospherejs.com/justan0therdave/materialize) having an identical description with the actual [official MaterializeCSS package](https://atmospherejs.com/materialize/materialize).

Can you please update the package description and describe in the README how this fork is different?

Thanks,
Dan

**Comment by justan0therdave** [comment]
Hi Dan,

I'll update the README accordingly as soon as I can.  I've stripped out all the CSS and it's just the JS files that I'm using from MaterializeCSS package.

Dave
